# pyproject.toml  (put in repo root)

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "filechat"
version = "0.1.0"
description = "Local/cloud file-editing workflow"
dependencies = []          # add runtime deps here as you go

[project.optional-dependencies]
dev = ["ruff", "pytest", "coverage"]